app_base:
    path: /
    controller: App\Controller\BaseController::index

afficher_calendrier:
    path: /afficher/calendrier
    controller: App\Controller\CalendrierController::index

obtenir_calendrier:
    path: /obtenir/calendrier
    controller: App\Controller\CalendrierController::afficherCalendrier