app_base:
    path: /
    controller: App\Controller\BaseController::index

afficher_calendrier:
    path: /afficher/calendrier
    controller: App\Controller\CalendrierController::index

ajouter_patient:
    path: /ajouter/patient
    controller: App\Controller\CalendrierController::ajouterPatient
    methods: [POST]

ajouter_rendezvous:
    path: /ajouter/rendezvous
    controller: App\Controller\CalendrierController::ajouterRendezVous
    methods: [POST]
